call "D:\development\flashattn\venv\Scripts\activate"
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"

SET FLASH_ATTENTION_DISABLE_SM80=TRUE
SET FLASH_ATTENTION_DISABLE_SM90=FALSE
SET FLASH_ATTENTION_DISABLE_HDIM64=FALSE
SET FLASH_ATTENTION_DISABLE_HDIM96=TRUE
SET FLASH_ATTENTION_DISABLE_HDIM128=TRUE
SET FLASH_ATTENTION_DISABLE_HDIM160=TRUE
SET FLASH_ATTENTION_DISABLE_HDIM192=TRUE
SET FLASH_ATTENTION_DISABLE_HDIM256=TRUE
SET FLASH_ATTENTION_DISABLE_HDIMDIFF64=FALSE
SET FLASH_ATTENTION_DISABLE_HDIMDIFF192=FALSE

SET MAX_JOBS=12
del /f install_log.txt
del /f build
python setup.py install  > install_log.txt 2>&1
python filter_errors.py
python filter_warnings.py
python fa3_validation.py